@tool
class_name AnimationIO

## Pure, stateless helpers for saving / loading multi-frame animation.
##
## Persistence model (all siblings of the spritesheet, named after it):
##   <sheet>.png            spritesheet — frames in a near-square grid
##   <sheet>.pxe.json       sidecar — frame_count, size, columns, fps, durations
##   <sheet>.frames.tres     Godot SpriteFrames resource (AnimatedSprite2D-ready)
##
## The dock places <sheet> inside a per-sprite folder so a project accumulates
## one tidy folder per animation. The spritesheet is the canonical pixel store
## (version-control friendly, lossless RGBA8); the sidecar makes the editor's
## round-trip exact; the SpriteFrames tres drops straight into an AnimatedSprite2D.
## Its failure never blocks the core save.

const _PNG_EXT := ".png"
const _SIDECAR_EXT := ".pxe.json"
const _SPRITEFRAMES_SUFFIX := ".frames.tres"
const _DEFAULT_FPS := 12.0
const _ANIM_NAME := "default"


## Saves a multi-frame document. Returns OK on success (spritesheet + sidecar
## always written; SpriteFrames best-effort). `path` may omit the extension.
static func save_animation(document: ImageDocument, path: String) -> Error:
	var frame_count := document.get_frame_count()
	if frame_count <= 0:
		return ERR_INVALID_PARAMETER
	if not path.ends_with(_PNG_EXT):
		path += _PNG_EXT

	var size := document.get_size()
	var fw := maxi(size.x, 1)
	var fh := maxi(size.y, 1)
	var cols := _compute_columns(frame_count)
	var rows := ceili(float(frame_count) / float(cols))

	var sheet := Image.create(fw * cols, fh * rows, false, Image.FORMAT_RGBA8)
	var durations: Array = []
	for i in frame_count:
		var f = document.frames[i]
		var col := i % cols
		var row := i / cols
		# blit_rect (not blend_rect) preserves exact alpha per pixel.
		sheet.blit_rect(f.image, Rect2i(0, 0, fw, fh), Vector2i(col * fw, row * fh))
		durations.append(f.duration)

	var err := sheet.save_png(path)
	if err != OK:
		push_error("PixelEditor: animation save failed (%d) to %s" % [err, path])
		return err

	_write_sidecar(path, frame_count, fw, fh, cols, durations, document.fps)
	_reimport(path)
	# The SpriteFrames .tres is generated by the dock once the async import lands
	# (see EditorDock._schedule_spriteframes) — doing it here synchronously would
	# race the import or recurse reimport_files().
	return OK


## Saves a single-frame (static) document as a plain PNG at `path`. No sprite
## folder, no sidecar, no .frames.tres — those are animation-only. If this path
## was previously saved as an animation, the now-stale sidecar / .tres are
## removed so the next open doesn't slice one frame into many. Returns OK on
## success.
static func save_static(document: ImageDocument, path: String) -> Error:
	if document.get_frame_count() < 1:
		return ERR_INVALID_PARAMETER
	if not path.ends_with(_PNG_EXT):
		path += _PNG_EXT
	_discard_animation_artifacts(path)
	# document.image aliases the active frame; for a single-frame doc that's frame 0.
	var err := document.image.save_png(path)
	if err != OK:
		push_error("PixelEditor: image save failed (%d) to %s" % [err, path])
		return err
	_reimport(path)
	return OK


## Loads an animation if a sidecar exists next to `png_path`; otherwise null so
## the caller can fall back to a plain single-image open.
static func try_load_animation(png_path: String) -> ImageDocument:
	# Sidecar lives beside the sheet (sheet.pxe.json), named after it.
	var sidecar := png_path.get_basename() + _SIDECAR_EXT
	if not FileAccess.file_exists(sidecar):
		return null
	var f := FileAccess.open(sidecar, FileAccess.READ)
	if f == null:
		return null
	var text := f.get_as_text()
	f.close()

	var parsed = JSON.parse_string(text)
	if typeof(parsed) != TYPE_DICTIONARY:
		push_error("PixelEditor: corrupt animation sidecar at %s" % sidecar)
		return null

	var count := int(parsed.get("frame_count", 0))
	var fw := int(parsed.get("frame_width", 0))
	var fh := int(parsed.get("frame_height", 0))
	var cols := int(parsed.get("columns", 0))
	var fps := float(parsed.get("fps", _DEFAULT_FPS))
	var durations = parsed.get("durations", [])
	if count <= 0 or fw <= 0 or fh <= 0:
		return null
	# Defence in depth: reject an absurd frame count before allocating anything.
	# A corrupt/hand-edited sidecar could claim thousands of frames.
	if count > 65536:
		push_error("PixelEditor: animation sidecar frame_count %d is unreasonably large" % count)
		return null

	var sheet := Image.load_from_file(png_path)
	if sheet == null:
		push_error("PixelEditor: failed to load spritesheet at %s" % png_path)
		return null
	# Trust-but-verify the sidecar against the actual sheet pixels: the declared
	# frame grid must fit inside the loaded sheet, otherwise a corrupt sidecar
	# would allocate `count` empty/blitted Images from out-of-bounds reads.
	if cols <= 0:
		cols = _compute_columns(count)
	if fw > sheet.get_width() or fh > sheet.get_height() or cols <= 0:
		push_error("PixelEditor: animation sidecar dimensions exceed spritesheet at %s" % png_path)
		return null
	var rows := ceili(float(count) / float(cols))
	if cols * fw > sheet.get_width() or rows * fh > sheet.get_height():
		push_error("PixelEditor: animation sidecar grid (%dx%d) exceeds spritesheet %s" % [cols, rows, png_path])
		return null

	var doc := ImageDocument.new()
	for i in count:
		var col := i % cols
		var row := i / cols
		var frame_img := Image.create(fw, fh, false, Image.FORMAT_RGBA8)
		frame_img.blit_rect(sheet, Rect2i(col * fw, row * fh, fw, fh), Vector2i(0, 0))
		var idx := doc.add_frame_with_image(frame_img)
		if i < durations.size():
			doc.frames[idx].duration = float(durations[i])
	doc.fps = fps
	doc.file_path = png_path
	doc.select_frame(0)
	return doc


# ----------------------------------------------------------------- internals

## Near-square grid keeps the sheet compact (avoiding ultra-wide strips) while
## staying trivially sliceable for both export and round-trip.
static func _compute_columns(count: int) -> int:
	return maxi(ceili(sqrt(float(count))), 1)


static func _write_sidecar(
	png_path: String,
	count: int,
	fw: int,
	fh: int,
	cols: int,
	durations: Array,
	fps: float
) -> void:
	var data := {
		"format": "godot-pixel-editor-animation",
		"version": 1,
		"frame_count": count,
		"frame_width": fw,
		"frame_height": fh,
		"columns": cols,
		"fps": fps,
		"durations": durations,
	}
	# Sidecar lives beside the sheet, named after it (sheet.pxe.json).
	var f := FileAccess.open(png_path.get_basename() + _SIDECAR_EXT, FileAccess.WRITE)
	if f == null:
		push_warning("PixelEditor: could not write animation sidecar for %s" % png_path)
		return
	f.store_string(JSON.stringify(data, "\t"))
	f.close()


static func _reimport(path: String) -> void:
	var res_path := ProjectSettings.localize_path(path)
	if res_path.is_empty():
		return
	var fs := EditorInterface.get_resource_filesystem()
	# Exactly ONE import trigger per save: a brand-new file isn't in the cache yet
	# (reimport_files() can't see it -> "Can't find file"), so we scan to discover
	# + import it; an already-imported file just needs a targeted refresh. Calling
	# reimport_files() twice in one frame throws "recursively ... not allowed".
	if not FileAccess.file_exists(res_path + ".import"):
		fs.scan()
	else:
		fs.reimport_files(PackedStringArray([res_path]))


## Removes the animation-only siblings of `png_path` (sidecar + .frames.tres).
## Called when a path that used to hold an animation is re-saved as a static
## image, so the stale metadata can't mis-direct a later open.
static func _discard_animation_artifacts(png_path: String) -> void:
	var sidecar := png_path.get_basename() + _SIDECAR_EXT
	if FileAccess.file_exists(sidecar):
		DirAccess.remove_absolute(sidecar)
	var sf := png_path.get_basename() + _SPRITEFRAMES_SUFFIX
	if FileAccess.file_exists(sf):
		DirAccess.remove_absolute(sf)


## Builds the AnimatedSprite2D-ready SpriteFrames resource from the spritesheet.
## Returns true on success, false if the texture isn't imported yet (the caller
## retries). No reimport here — the single trigger lives in _reimport(); calling
## reimport_files() again would recurse.
static func generate_spriteframes(
	png_path: String,
	fw: int,
	fh: int,
	durations: Array,
	fps: float
) -> bool:
	var res_path := ProjectSettings.localize_path(png_path)
	var tex = load(res_path)
	if tex == null:
		return false
	var cols := _compute_columns(durations.size())
	var sf := SpriteFrames.new()
	if sf.has_animation(_ANIM_NAME):
		sf.remove_animation(_ANIM_NAME)
	sf.add_animation(_ANIM_NAME)
	sf.set_animation_loop(_ANIM_NAME, true)
	sf.set_animation_speed(_ANIM_NAME, fps)
	for i in durations.size():
		var col := i % cols
		var row := i / cols
		var at := AtlasTexture.new()
		at.atlas = tex
		at.region = Rect2(col * fw, row * fh, fw, fh)
		sf.add_frame(_ANIM_NAME, at, float(durations[i]))
	# res:// path keeps the baked AtlasTexture references portable.
	var err := ResourceSaver.save(sf, res_path.get_basename() + _SPRITEFRAMES_SUFFIX)
	if err != OK:
		push_warning("PixelEditor: SpriteFrames export failed (%d)" % err)
		return false
	return true
